# Generated by Django 3.2.6 on 2022-02-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('game_info', models.CharField(max_length=255, verbose_name='Об игре')),
                ('genre', models.CharField(choices=[('arcade', 'Аркада'), ('strategy', 'Стратегия'), ('sport', 'Спорт'), ('adventure', 'Приключения'), ('rpg', 'Ролевые')], default='arcade', max_length=255, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_image', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='media/images', verbose_name='Изображение товара')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
