# Generated by Django 4.0.2 on 2022-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_muster_app', '0002_alter_games_options_gameuser_avatar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='user_avatar_image'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=124, verbose_name='Gender'),
        ),
    ]
