# Generated by Django 3.2.6 on 2022-02-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_muster_app', '0002_auto_20220211_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='Об игре'),
        ),
    ]
