# Generated by Django 4.0.2 on 2022-03-10 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_muster_app', '0003_gameuser_age_gameuser_gender_alter_gameuser_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='birthday',
            field=models.DateField(default=0, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
