# Generated by Django 4.0.2 on 2022-05-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_muster_app', '0003_alter_gameuser_avatar_image_alter_gameuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=124, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='genre_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='Genre id'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='platform_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='Platform id'),
        ),
    ]
