# Generated by Django 3.2.6 on 2022-02-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_muster_app', '0003_alter_games_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.FloatField(default=0, verbose_name='Оценка пользователей')),
                ('critics', models.FloatField(default=0, verbose_name='Оценка критиков')),
                ('users_count', models.IntegerField(default=0, verbose_name='Кол-во оценок пользователей')),
                ('critics_count', models.IntegerField(default=0, verbose_name='Кол-во оценок критиков')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.AddField(
            model_name='games',
            name='image',
            field=models.ImageField(default=1, upload_to='media/games', verbose_name='Постер игры'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media/images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='games',
            name='ratings',
            field=models.ManyToManyField(to='game_muster_app.Ratings'),
        ),
    ]
