# Generated by Django 4.0.2 on 2022-05-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_muster_app', '0004_alter_gameuser_gender_alter_genres_genre_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='genre_id',
            field=models.IntegerField(unique=True, verbose_name='Genre id'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='platform_id',
            field=models.IntegerField(unique=True, verbose_name='Platform id'),
        ),
    ]
