# Generated by Django 3.2.6 on 2022-02-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_muster_app', '0004_auto_20220211_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='ratings',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='ScreenShots',
        ),
        migrations.DeleteModel(
            name='Games',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
