# Generated by Django 4.0.2 on 2022-05-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_muster_app', '0005_alter_genres_genre_id_alter_platforms_platform_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='aggregated_rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Game aggregated rating'),
        ),
        migrations.AlterField(
            model_name='games',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Game rating'),
        ),
    ]
