# Generated by Django 4.0.2 on 2022-03-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_muster_app', '0005_alter_gameuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='gameuser',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
