# Generated by Django 4.0.2 on 2022-05-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_muster_app', '0006_alter_games_aggregated_rating_alter_games_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_name',
            field=models.CharField(max_length=256, verbose_name='Game name'),
        ),
        migrations.AlterField(
            model_name='games',
            name='release_dates',
            field=models.CharField(max_length=256, null=True, verbose_name='Game release dates'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='genre_name',
            field=models.CharField(max_length=256, verbose_name='Genre name'),
        ),
        migrations.AlterField(
            model_name='platforms',
            name='platform_name',
            field=models.CharField(max_length=256, verbose_name='Platform name'),
        ),
    ]
