# Generated by Django 4.0.2 on 2022-03-29 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_muster_app', '0006_delete_test_gameuser_email_verify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='email_verify',
            field=models.BooleanField(default=False, verbose_name='Email verification status'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
