# Generated by Django 4.0.2 on 2022-03-30 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_muster_app', '0007_alter_gameuser_options_alter_gameuser_email_verify_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuser',
            name='age',
        ),
        migrations.CreateModel(
            name='UserFavoriteGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(default=0, verbose_name='User games')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite_game', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'User wishlist',
                'verbose_name_plural': 'Users wishlists',
            },
        ),
    ]
