# Generated by Django 4.0.2 on 2022-04-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_muster_app', '0008_remove_gameuser_age_userfavoritegames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFavoriteGames',
        ),
    ]
