# Generated by Django 4.0.2 on 2022-04-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_muster_app', '0010_games_genres_platforms_userfavoritegames_screenshots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='release_dates',
            field=models.CharField(default=1, max_length=124, verbose_name='Game release dates'),
            preserve_default=False,
        ),
    ]
